export const menuItemsData = [
  {
    id: 1,
    name: "Mediterranean  Salad",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/bigBurger.png",
  },
  {
    id: 2,
    name: "Summer Asian Slaw",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/bowl1.png",
  },
  {
    id: 3,
    name: "Burger",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/bowl2.png",
  },
  {
    id: 4,
    name: "white sauce pasta",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/bowl3.png",
  },
  {
    id: 5,
    name: "butterfly pasta",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/bowl4.png",
  },
  {
    id: 6,
    name: "tooty fruity bowl",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/fruits.png",
  },
  {
    id: 7,
    name: "granola cereal bowl",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/granola cereal bowl.png",
  },
  {
    id: 8,
    name: "palm bowl",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/kisspng-01.png",
  },
  {
    id: 9,
    name: "tigela smoothie",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/kisspng-02.png",
  },
  {
    id: 10,
    name: "breakfast cereal",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/kisspng-03.png",
  },
  {
    id: 11,
    name: "cuisine of hawaii",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/kisspng-04.png",
  },
  {
    id: 12,
    name: "fried chicken",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/kisspng-05.png",
  },
  {
    id: 13,
    name: "greek salad",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/kisspng-06.png",
  },
  {
    id: 14,
    name: "hamburger",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/kisspng-07.png",
  },
  {
    id: 15,
    name: "israeli salad",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/kisspng-09.png",
  },
  {
    id: 16,
    name: "Pizza Pasta",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/kisspng-08.png",
  },
  {
    id: 17,
    name: "Pizza",
    info: "spicey with garlic and then deep fried to crispy perfection",
    price: 24,
    img: "/images/pizza.png",
  },
];
